In [ ]:
import mysql.connector

msql = mysql.connector.connect(
    host='localhost',
    user='root',
    password=''
)
cursor=msql.cursor()

cursor.execute("SHOW DATABASES")
for i in cursor:
    print(i,end=' ')

# def creat():
#     name=input("enter the database name:")
#     cd="CREATE DATABASE "
#     cursor.execute(cd+name)
#     print("created")

namedb = input("select the DATABASE:")
use ="USE " 
cursor.execute(use+namedb)
print("now you will use DATABASE")

tname=input("Enter The Table Name:")
ct="CREATE TABLE "
pro=" (name VARCHAR(255),product VARCHAR(255))"
cursor.execute(ct+tname+pro)
print("now table is rady.")

tname3=input("Select The Table Name:")
td=eval(input("enter the table data number:"))
val=("VISHAL","KIDY")
sql="INSERT INTO",tname3,"(name,product) VALUES(%s,%s)"
if 1==td:
    cursor.execute(sql,val)
#         break
    msql.commit()
    print(cursor.rowcount,"record inserted.")
else: 
    val=input("enter the values like this [(name,product),(name,product)]:")
    cursor.executemany(ii+tname+np,val)
    msql.commit()
    print(cursor.rowcount,"record inserted.")
        
# def cr():
print(cursor.rowcount,"record")

# def viwed():
#     tname=input("Select The Table Name:")
#     slct="SELECT * FROM "
#     curser.execute(slct+tname)
#     mr=cursor.fetchall()
#     for i in mr:
#         print(i)

In [ ]:
import mysql.connector

msql = mysql.connector.connect(
    host='localhost',
    user='root',
    password=''
)
cursor=msql.cursor()

cursor.execute("SHOW DATABASES")
for i in cursor:
    print(i,end=' ')

# def creat():
#     name=input("enter the database name:")
#     cd="CREATE DATABASE "
#     cursor.execute(cd+name)
#     print("created")

namedb = input("select the DATABASE:")
use ="USE " 
cursor.execute(use+namedb)
print("now you will use DATABASE")

tname=input("Enter The Table Name:")
ct="CREATE TABLE "
pro=" (name VARCHAR(255),product VARCHAR(255))"
cursor.execute(ct+tname+pro)
print("now table is rady.")

tname3=input("Select The Table Name:")
td=eval(input("enter the table data number:"))
val=("VISHAL","KIDY")
sql="INSERT INTO",tname3,"(name,product) VALUES(%s,%s)"
if 1==td:
    cursor.execute(sql,val)
#         break
    msql.commit()
    print(cursor.rowcount,"record inserted.")
else: 
    val=input("enter the values like this [(name,product),(name,product)]:")
    cursor.executemany(ii+tname+np,val)
    msql.commit()
    print(cursor.rowcount,"record inserted.")
        
# def cr():
print(cursor.rowcount,"record")

# def viwed():
#     tname=input("Select The Table Name:")
#     slct="SELECT * FROM "
#     curser.execute(slct+tname)
#     mr=cursor.fetchall()
#     for i in mr:
#         print(i)